config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :books
  root 'books#index'

  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_many :reviews
  
end

app/models/review.rb
class Review < ApplicationRecord
  
  belongs_to :book
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def index 
    @books = Book.all
  end

  def show 
    @book = Book.find(params[:id])
    @reviews = @book.reviews
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<% @books.each do |book| %>
  <div class="book">
    <div class="row">
      <div class="col-md-1">
        <p class="rank-this-week"> <%= book.rank_this_week %> </p>
      </div>
      <div class="col-md-9">
        <p class="title"><%= book.title %> </p>
        <p class="author">by <%= book.author%> </p>
        <p class="publisher">(<%= book.publisher%> )</p>
        <p class="description"> <%= book.description %> </p>
        <%= link_to 'See all Editorial Reviews', book_path(book) %>
      </div>
      <div class="col-md-2">
        <p class="weeks-on-list"> <%= book.weeks_on_list %> weeks on list</p>
      </div>
    </div>
  </div>
<% end %>

app/views/books/show.html.erb
<div class="book">
  <p class="title"> <%= @book.title %> </p>
  <p class="author">by <%= @book.author %>   </p>
  <p class="publisher">(<%= @book.publisher %> )</p>
  <p class="description"> <%= @book.description %> </p>
</div>

<div class="reviews">
  <% @reviews.each do |review| %>
    <div class="review">
      <p class="author"> <%= review.author %></p>
      <p class="comment"> <%= review.comment %> </p>
    </div>
  <% end %>
  <%= link_to "Back", root_path  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>